config/routes.rb
Rails.application.routes.draw do
    get '/items/new' => 'items#new'
    get '/items/:id' => 'items#show', as: :item
    patch '/items/:id' => 'items#update'
    delete '/items/:id' => 'items#destroy'
    get '/items/:id/edit' => 'items#edit'
    get '/items' => 'items#index'
    post '/items' => 'items#create'

    root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
    end

    def show
        @item = Item.find(params[:id])
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        @item.save #うえで入れた情報をsaveメソッドで処理 DBに登録される
        redirect_to @item #createはviewがないのでリダイレクト処理を行う
    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        @item = Item.find(params[:id]) #更新かける前に情報を取得
        @item.update(item_params) #25行目で狙いを定めて、updateをかけるよ、内容はitem_paramsだよ
        redirect_to @item
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to items_url #rake routesでプレフィックスを確認
    end

    private
    def item_params
        params.require(:item).permit(:name, :description, :price, :seller_id, :email, :image_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
    <p>商品名：<%= f.text_field :name %></p>
    <p>商品詳細：<%= f.text_area :description %></p>
    <p>価格：<%= f.number_field :price %></p>
    <p>売り手ID：<%= f.number_field :seller_id %></p>
    <p>電子メール：<%= f.text_field :email %></p>
    <p>商品画像URL：<%= f.text_field :image_url %></p>
    <%= f.submit '登録' %>
<% end %>

app/views/items/edit.html.erb
<h1>商品編集</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<h2>一覧</h2>
<ul>
<% @items.each do |item| %>
    <li>
        <%= link_to item.name, item_path(item.id) %>
        <span id="alert"><%= link_to '削除する', item_path(item.id), method: :delete %></span>
    </li>
<% end %>
</ul>

app/views/items/new.html.erb
<h1>商品新規登録</h1>
<%= render 'form' %>

app/views/items/show.html.erb
<p><b>商品名：<%= @item.name %></b></p>
<p><b>商品詳細：<%= @item.description %></b></p>
<p><b>価格：<%= @item.price %></b></p>
<p><b>売り手ID：<%= @item.seller_id %></b></p>
<p><b>電子メール：<%= @item.email %></b></p>
<%= link_to '削除',item_path(@item), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>